{% set name = "redbox" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redbox-{{ version }}.tar.gz
  sha256: 17005f8cfe8acba992b649e5682b2dd4bff937d67df3fd8496e187cae4f19d60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pydantic
    - python >={{ python_min }}

test:
  imports:
    - redbox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Miksus/red-box
  doc_url: https://red-box.readthedocs.io/
  summary: Email box reading library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
